# Generated by Django 2.2.20 on 2024-09-06 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repository',
            name='configuration',
        ),
    ]
