# Generated by Django 2.2.20 on 2024-09-06 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0002_remove_repository_configuration'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='configuration',
            field=models.TextField(blank=True, null=True),
        ),
    ]
