# Generated by Django 2.2.20 on 2024-09-06 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0003_repository_configuration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repository',
            name='configuration',
        ),
    ]
