# Generated by Django 2.2.20 on 2024-10-03 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0005_repository_endpoint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repository',
            name='endpoint',
            field=models.CharField(max_length=255, verbose_name='Endpoint'),
        ),
    ]
