# Generated by Django 2.2.20 on 2024-10-08 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0006_auto_20241003_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='client_id',
            field=models.CharField(default='OAUTHCLIENT58', max_length=50, verbose_name='Client ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='repository',
            name='client_secret',
            field=models.CharField(default='a265efd1-0344-4e6f-80c5-3c05a945932d', max_length=255, verbose_name='Client Secret'),
            preserve_default=False,
        ),
    ]
