# Generated by Django 2.2.20 on 2024-11-07 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0007_auto_20241008_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='giles_endpoint',
            field=models.CharField(default='https://diging.asu.edu/geco-giles-staging/', max_length=255, verbose_name='Giles Endpoint'),
            preserve_default=False,
        ),
    ]
