# Generated by Django 2.2.20 on 2024-11-07 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0008_repository_giles_endpoint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repository',
            name='endpoint',
            field=models.CharField(help_text='Enter the endpoint URL without a trailing slash', max_length=255, verbose_name='Endpoint'),
        ),
        migrations.AlterField(
            model_name='repository',
            name='giles_endpoint',
            field=models.CharField(help_text='Enter the endpoint URL without a trailing slash', max_length=255, verbose_name='Giles Endpoint'),
        ),
    ]
