FROM python:3.7

RUN apt-get update && apt-get install -y \
    supervisor \
    && rm -rf /var/lib/apt/lists/*

COPY . /vogon

COPY supervisord.conf /etc/supervisor/conf.d/supervisord.conf

COPY startup.sh /vogon/startup.sh

RUN chmod +x /vogon/startup.sh

WORKDIR /vogon

CMD ["/usr/bin/supervisord", "-c", "/etc/supervisor/supervisord.conf"]
