FROM python:3.7
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /vogon

RUN apt-get update && apt-get install -y supervisor && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

COPY supervisord.conf /etc/supervisor/conf.d/supervisord.conf

COPY startup-prod.sh /vogon/startup-prod.sh
RUN ["chmod", "+x", "/vogon/startup-prod.sh"]

ENTRYPOINT ["/vogon/startup-prod.sh"]