version: "3.9"
   
services:
  db:
    image: postgres
    platform: linux/amd64
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
  web:
    build: .
    platform: linux/amd64
    command: tail -f /dev/null
    volumes:
      - .:/vogon
      - ./data/files:/data/files
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - DATA_PATH=/data/files/
      - MEDIA_URL_PATH=/dashboard/files/
      - MEDIA_ROOT_PATH=files
    depends_on:
      - db