# Generated by Django 2.2.20 on 2024-08-22 15:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CitesphereAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('citesphere_user_id', models.CharField(help_text='Unique identifier for the Citesphere user', max_length=255)),
                ('access_token', models.CharField(help_text='OAuth access token', max_length=255)),
                ('refresh_token', models.CharField(help_text='OAuth refresh token', max_length=255)),
                ('token_expires_at', models.DateTimeField(help_text='The datetime the access token expires')),
                ('extra_data', models.TextField(default='{}', help_text='Any extra data returned by Citesphere in JSON format')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citesphere_account', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
