# Generated by Django 2.2.20 on 2024-08-23 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('external_accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=255)),
                ('version', models.IntegerField()),
                ('num_items', models.IntegerField()),
                ('date_created', models.DateTimeField()),
                ('date_modified', models.DateTimeField()),
                ('type', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('citesphere_accounts', models.ManyToManyField(related_name='groups', to='external_accounts.CitesphereAccount')),
            ],
        ),
    ]
