# Generated by Django 2.2.20 on 2024-08-23 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('external_accounts', '0002_group'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Group',
            new_name='CitesphereGroup',
        ),
    ]
