# Generated by Django 2.2.20 on 2024-08-27 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('external_accounts', '0003_auto_20240823_2103'),
    ]

    operations = [
        migrations.AddField(
            model_name='citespheregroup',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
        migrations.CreateModel(
            name='CitesphereCollection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection_id', models.CharField(max_length=255, unique=True)),
                ('key', models.CharField(max_length=100)),
                ('version', models.IntegerField()),
                ('content_version', models.IntegerField(default=0)),
                ('number_of_collections', models.IntegerField(default=0)),
                ('number_of_items', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=255)),
                ('parent_collection_key', models.CharField(blank=True, max_length=100, null=True)),
                ('last_modified', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collections', to='external_accounts.CitesphereGroup')),
            ],
        ),
    ]
