# Generated by Django 2.2.20 on 2024-08-27 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('external_accounts', '0004_auto_20240827_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citespherecollection',
            name='collection_id',
            field=models.CharField(max_length=255),
        ),
    ]
