# Generated by Django 2.2.20 on 2024-08-27 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('external_accounts', '0005_auto_20240827_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='citespheregroup',
            name='sync_status',
            field=models.CharField(default='PENDING', max_length=100),
        ),
    ]
