# Generated by Django 2.2.20 on 2024-08-27 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('external_accounts', '0007_citesphereitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citesphereitem',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='citesphereitem',
            name='dateAdded',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
