# Generated by Django 2.2.20 on 2024-10-08 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0007_auto_20241008_1713'),
        ('external_accounts', '0011_auto_20241008_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='citesphereaccount',
            name='repository',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='citesphere_accounts', to='repository.Repository'),
            preserve_default=False,
        ),
    ]
