# Generated by Django 4.2.16 on 2025-05-01 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('external_accounts', '0012_citesphereaccount_repository'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citesphereaccount',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
