# Generated by Django 2.2.20 on 2025-02-07 04:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('external_accounts', '0012_citesphereaccount_repository'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConceptpowerAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conceptpower_account', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
