# Generated by Django 2.2.20 on 2025-05-22 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('external_accounts', '0013_conceptpoweraccount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conceptpoweraccount',
            old_name='password',
            new_name='_password',
        ),
        migrations.AlterField(
            model_name='conceptpoweraccount',
            name='_password',
            field=models.CharField(db_column='password', max_length=255),
        ),
        migrations.AlterModelTable(
            name='conceptpoweraccount',
            table='external_accounts_conceptpoweraccount',
        ),
    ]
