# Generated by Django 4.2.16 on 2025-05-23 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('external_accounts', '0013_alter_citesphereaccount_id'),
        ('external_accounts', '0014_auto_20250522_1857'),
    ]

    operations = [
    ]
