# Generated by Django 4.2.16 on 2025-05-23 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('external_accounts', '0015_merge_20250523_1917'),
    ]

    operations = [
        migrations.AddField(
            model_name='conceptpoweraccount',
            name='_encryption_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='conceptpoweraccount',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterModelTable(
            name='conceptpoweraccount',
            table=None,
        ),
    ]
