# Generated by Django 4.2.16 on 2025-06-06 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('external_accounts', '0016_conceptpoweraccount__encryption_key_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conceptpoweraccount',
            name='_encryption_key',
        ),
    ]
