# Generated by Django 2.2.20 on 2025-02-28 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concepts', '0004_auto_20190625_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concept',
            name='concept_state',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Rejected', 'Rejected'), ('Resolved', 'Resolved'), ('Merged', 'Merged')], default='Pending', max_length=10),
        ),
    ]
