# Generated by Django 2.2.20 on 2025-03-04 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concepts', '0005_auto_20250228_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concept',
            name='concept_state',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Rejected', 'Rejected'), ('Resolved', 'Resolved'), ('Merged', 'Merged'), ('Flagged', 'Flagged')], default='Pending', max_length=10),
        ),
    ]
