# Generated by Django 2.2.20 on 2025-02-07 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('concepts', '0005_conceptpoweraccount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ConceptpowerAccount',
        ),
    ]
