# Generated by Django 2.2.20 on 2025-03-20 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('concepts', '0005_concept_createdby'),
        ('concepts', '0005_auto_20250228_2309'),
    ]

    operations = [
    ]
