# Generated by Django 2.2.20 on 2025-03-04 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concepts', '0006_auto_20250304_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='concept',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
