# Generated by Django 2.2.20 on 2025-03-11 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('concepts', '0007_concept_comment'),
        ('concepts', '0005_concept_createdby'),
    ]

    operations = [
    ]
