# Generated by Django 2.2.20 on 2025-04-04 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('concepts', '0007_concept_comment'),
        ('concepts', '0006_merge_20250320_1618'),
    ]

    operations = [
    ]
