# Generated by Django 2.2.20 on 2025-04-15 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('concepts', '0009_auto_20250410_1546'),
        ('concepts', '0006_delete_conceptpoweraccount'),
    ]

    operations = [
    ]
