# Generated by Django 2.2.20 on 2025-04-15 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('concepts', '0010_auto_20250410_1612'),
        ('concepts', '0008_merge_20250311_2053'),
    ]

    operations = [
    ]
