# Generated by Django 4.2.16 on 2025-06-03 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('concepts', '0010_auto_20250410_1612'),
        ('concepts', '0010_merge_20250415_1733'),
    ]

    operations = [
    ]
