# Generated by Django 2.2.20 on 2024-09-05 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('external_accounts', '0010_auto_20240827_1855'),
        ('annotations', '0035_relationtemplate_use_in_mass_assignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportedCitesphereItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('import_date', models.DateTimeField(auto_now_add=True, help_text='The datetime the item was imported')),
                ('source', models.CharField(help_text='The source from which the item was imported', max_length=255)),
                ('processing_notes', models.TextField(blank=True, help_text='Notes on any processing done on the item', null=True)),
                ('citesphere_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='imported_item', to='external_accounts.CitesphereItem')),
            ],
        ),
    ]
