# Generated by Django 2.2.20 on 2024-10-08 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0040_auto_20240906_1641'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImportedCitesphereItem',
        ),
    ]
