# Generated by Django 2.2.20 on 2024-11-12 17:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0041_delete_importedcitesphereitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='textcollection',
            name='collaborators',
            field=models.ManyToManyField(blank=True, related_name='collaborations', to=settings.AUTH_USER_MODEL),
        ),
    ]
