# Generated by Django 2.2.20 on 2024-10-29 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0041_delete_importedcitesphereitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='relationset',
            name='status',
            field=models.CharField(choices=[('not_ready', 'Not Ready'), ('ready_to_submit', 'Ready to Submit'), ('submitted', 'Submitted')], default='not_ready', max_length=20),
        ),
    ]
