# Generated by Django 2.2.20 on 2024-11-08 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0042_vogonuser_vogon_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vogonuser',
            name='vogon_admin',
            field=models.BooleanField(default=False, help_text='This fi user has admin permissions within the application without Django admin access.'),
        ),
    ]
