# Generated by Django 2.2.20 on 2024-12-13 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0042_textcollection_collaborators'),
        ('annotations', '0043_remove_relationset_pending'),
    ]

    operations = [
    ]
