# Generated by Django 2.2.20 on 2024-12-13 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0044_auto_20241108_2155'),
        ('annotations', '0042_textcollection_collaborators'),
    ]

    operations = [
    ]
