# Generated by Django 4.2.16 on 2025-05-02 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0045_merge_20241213_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repository',
            name='manager',
            field=models.CharField(choices=[], max_length=255),
        ),
        migrations.AlterField(
            model_name='textcollection',
            name='texts',
            field=models.ManyToManyField(blank=True, related_name='partOf', to='annotations.text'),
        ),
    ]
