# Generated by Django 2.2.20 on 2025-01-24 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0044_merge_20241213_1539'),
        ('annotations', '0045_merge_20241213_1723'),
    ]

    operations = [
    ]
