# Generated by Django 2.2.20 on 2025-04-11 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0045_merge_20241213_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentposition',
            name='position_type',
            field=models.CharField(choices=[('TI', 'Token IDs'), ('BB', 'Bounding box'), ('XP', 'XPath'), ('CO', 'Character offsets'), ('WD', 'Whole document'), ('TXP', 'TEI XPointer')], max_length=3),
        ),
    ]
