# Generated by Django 4.2.16 on 2025-05-01 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0046_merge_20250124_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repository',
            name='manager',
            field=models.CharField(choices=[], max_length=255),
        ),
    ]
