# Generated by Django 2.2.20 on 2025-04-10 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0046_merge_20250124_2230'),
    ]

    operations = [
        migrations.AddField(
            model_name='relationtemplate',
            name='default_mapping',
            field=models.TextField(blank=True, null=True),
        ),
    ]
