# Generated by Django 4.2.16 on 2025-05-23 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0046_alter_repository_manager_alter_textcollection_texts'),
        ('annotations', '0046_auto_20250411_1857'),
    ]

    operations = [
    ]
