# Generated by Django 4.2.16 on 2025-05-01 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0047_alter_repository_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textcollection',
            name='texts',
            field=models.ManyToManyField(blank=True, related_name='partOf', to='annotations.text'),
        ),
    ]
