# Generated by Django 2.2.20 on 2025-04-17 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0047_relationtemplate_default_mapping'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_type', models.CharField(choices=[('Node', 'Node'), ('URI', 'URI')], max_length=10)),
                ('subject_value', models.CharField(max_length=255)),
                ('predicate_type', models.CharField(choices=[('Node', 'Node'), ('URI', 'URI')], max_length=10)),
                ('predicate_value', models.CharField(max_length=255)),
                ('object_type', models.CharField(choices=[('Node', 'Node'), ('URI', 'URI')], max_length=10)),
                ('object_value', models.CharField(max_length=255)),
            ],
        ),
    ]
