# Generated by Django 2.2.20 on 2025-04-17 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0048_defaultmapping'),
    ]

    operations = [
        migrations.AddField(
            model_name='relationtemplate',
            name='structured_mapping',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='templates', to='annotations.DefaultMapping'),
        ),
    ]
