# Generated by Django 4.2.16 on 2025-05-15 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0046_alter_repository_manager_alter_textcollection_texts'),
        ('annotations', '0048_alter_textcollection_texts'),
    ]

    operations = [
    ]
