# Generated by Django 4.2.16 on 2025-05-21 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0050_merge_20250513_1712'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relationtemplate',
            name='default_mapping',
        ),
    ]
