# Generated by Django 4.2.16 on 2025-05-21 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0051_remove_relationtemplate_default_mapping'),
    ]

    operations = [
        migrations.RenameField(
            model_name='relationtemplate',
            old_name='structured_mapping',
            new_name='default_mapping',
        ),
    ]
