# Generated by Django 4.2.16 on 2025-06-06 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0049_merge_20250515_1822'),
        ('annotations', '0052_rename_structured_mapping_relationtemplate_default_mapping'),
    ]

    operations = [
    ]
